// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inqztezgmftnatjydjhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucXp0ZXpnbWZ0bmF0anlkamhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDI2MDMsImV4cCI6MjA2NzkxODYwM30.M_dtTJmG43jlMGsEtaU6tc_n4zxSOgDML3Cxktw6N0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});